spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demodb?serverTimezone=UTC
    username: root
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: 'true'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: 'true'
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
logging:  
    org:
      generate-ddl: 'true'     
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE
h2:
    console:
    enabled: true
server:
  port: 8081